const GET_ALL_REMINDERS = 'GET_ALL_REMINDERS';
const GET_ALL_RELATIVES = 'GET_ALL_RELATIVES';
const GET_CARETAKER = 'GET_CARETAKER';
const GET_ALL_CHATS = 'GET_ALL_CHATS';

export { GET_ALL_REMINDERS, GET_ALL_RELATIVES, GET_CARETAKER, GET_ALL_CHATS };